name: Build and run unit tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: 'Setup JDK 17'
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: 'Setup Gradle'
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5.1

      - name: 'Execute Gradle build'
        run: gradle clean build
